version: 2
updates:
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: mix
    directory: "/example"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
