name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ["22.3", "23.3", "24.2"]
        elixir: ["1.11.4", "1.12.3", "1.13.1"]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Formatter
        run: mix format --check-formatted
      - name: Run Linter
        run: mix credo
      - name: Run Hex Audit
        run: mix hex.audit
      - name: Generate docs
        run: mix docs
      - name: Run Tests
        run: mix coveralls.github
